// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Domicilio
{
    public int Id { get; set; }

    public string Calle { get; set; }

    public int Numero { get; set; }

    public string Piso { get; set; }

    public string Departamento { get; set; }

    public int IdProvincia { get; set; }

    public virtual Provincia IdProvinciaNavigation { get; set; }

    public virtual ICollection<Usuario> Usuario { get; set; } = new List<Usuario>();
}