// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


namespace Models.Models;

public partial class Factura
{
    public int Id { get; set; }

    public float MontoTotal { get; set; }

    public DateTime Fecha { get; set; }

    public long Numero { get; set; }

    public virtual ICollection<Pedido> Pedido { get; set; } = new List<Pedido>();
}