// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Imagen
{
    public int Id { get; set; }

    public List<byte[]> Url { get; set; }

    public int IdProducto { get; set; }

    public virtual Producto IdProductoNavigation { get; set; }
}