// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


namespace Models.Models;

public partial class Pedido
{
    public int Id { get; set; }

    public long Numero { get; set; }

    public float Total { get; set; }

    public DateTime FechaCreacion { get; set; }

    public int IdCliente { get; set; }

    public int IdFactura { get; set; }

    public virtual Usuario IdClienteNavigation { get; set; }

    public virtual Factura IdFacturaNavigation { get; set; }

    public virtual ICollection<PedidoDetalle> PedidoDetalle { get; set; } = new List<PedidoDetalle>();
}