// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Usuario
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Email { get; set; }

    public long Dni { get; set; }

    public long Telefono { get; set; }

    public string Contrasenia { get; set; }

    public int IdDomicilio { get; set; }

    public int IdRol { get; set; }

    public virtual Domicilio IdDomicilioNavigation { get; set; }

    public virtual Rol IdRolNavigation { get; set; }

    public virtual ICollection<Pedido> Pedido { get; set; } = new List<Pedido>();
}